import { TourApiBodyPaged, TourApiResponse } from './common'

type DetailIntroBody = TourApiBodyPaged<DetailIntroItem>

export type DetailIntroItem = {
  chkpetculture: string
  eventhomepage: string
  eventplace: string
  parkingleports: string
  reservation: string
  restdateleports: string
  eventstartdate: string
  festivalgrade: string
  karaoke: string
  discountinfofood: string
  firstmenu: string
  infocenterfood: string
  kidsfacility: string
  opendatefood: string
  opentimefood: string
  packing: string
  parkingfood: string
  reservationfood: string
  chkcreditcardculture: string
  scaleleports: string
  usefeeleports: string
  discountinfofestival: string
  chkcreditcardfood: string
  eventenddate: string
  playtime: string
  chkbabycarriageculture: string
  roomcount: string
  reservationlodging: string
  reservationurl: string
  roomtype: string
  scalelodging: string
  subfacility: string
  barbecue: string
  beauty: string
  beverage: string
  bicycle: string
  campfire: string
  fitness: string
  placeinfo: string
  parkinglodging: string
  pickup: string
  publicbath: string
  opendate: string
  parking: string
  restdate: string
  usetimeleports: string
  foodplace: string
  infocenterlodging: string
  restdatefood: string
  scalefood: string
  seat: string
  smoking: string
  treatmenu: string
  lcnsno: string
  contentid: string
  contenttypeid: string
  accomcount: string
  chkbabycarriage: string
  chkcreditcard: string
  chkpet: string
  expagerange: string
  expguide: string
  heritage1: string
  heritage2: string
  heritage3: string
  infocenter: string
  taketime: string
  theme: string
  accomcountleports: string
  chkbabycarriageleports: string
  chkcreditcardleports: string
  chkpetleports: string
  expagerangeleports: string
  infocenterleports: string
  openperiod: string
  parkingfeeleports: string
  program: string
  spendtimefestival: string
  sponsor1: string
  sponsor1tel: string
  discountinfo: string
  infocenterculture: string
  parkingculture: string
  parkingfee: string
  restdateculture: string
  usefee: string
  usetimeculture: string
  scale: string
  spendtime: string
  agelimit: string
  bookingplace: string
  useseason: string
  usetime: string
  accomcountculture: string
  sponsor2: string
  sponsor2tel: string
  subevent: string
  usetimefestival: string
  distance: string
  infocentertourcourse: string
  schedule: string
  publicpc: string
  sauna: string
  seminar: string
  sports: string
  refundregulation: string
  chkbabycarriageshopping: string
  chkcreditcardshopping: string
  chkpetshopping: string
  culturecenter: string
  fairday: string
  infocentershopping: string
  opendateshopping: string
  opentime: string
  parkingshopping: string
  restdateshopping: string
  restroom: string
  saleitem: string
  saleitemcost: string
  scaleshopping: string
  shopguide: string
  checkintime: string
  checkouttime: string
  chkcooking: string
  accomcountlodging: string
}

export type DetailIntro = TourApiResponse<DetailIntroBody>
